language: python

sudo: false
group: edge
dist: trusty

matrix:
    include:
        # These are just to make travis's UI a bit prettier
        - python: 2.7
          env: TOXENV=py27 CC=gcc
        - python: 3.3
          env: TOXENV=py33 CC=gcc
        - python: 3.4
          env: TOXENV=py34 CC=gcc
        - python: 3.5
          env: TOXENV=py35 CC=gcc
        - python: pypy
          env: TOXENV=pypy CC=gcc
        - python: 2.7
          env: TOXENV=py27 CC=clang
        - python: 3.3
          env: TOXENV=py33 CC=clang
        - python: 3.4
          env: TOXENV=py34 CC=clang
        - python: 3.5
          env: TOXENV=py35 CC=clang
        - python: pypy
          env: TOXENV=pypy CC=clang
        - env: TOXENV=packaging

install: .travis/install.sh

script: .travis/run.sh

after_success: codecov
